### PR TITLE
Feature 94 - Solution to Issue #94

### PR DESCRIPTION
**Pull request by dash-**
Reworked ResultSet.getObjectIter() method.  Generally refactored it, but also added logic to return null for integers rather than zero, which is detected via getObjectSync().

Also includes style fixes (tabs to spaces) for two files (lib/databasemetadata.js, lib/statement.js).

### CODE REVIEW

**Comment by dash-** [comment]
So this failed because two test runs had an ECONNRESET during the initial npm install.  So it doesn't seem related to any of the changes.  I'd like to tell travis.ci to "try again" but I'm not quite sure how yet.

**Comment by dash-** [comment]
Closed and re-opened to trigger Travis.ci rebuild.

**Comment by dash-** [comment]
Failed again due to network hangup.  Closing and re-opening again to re-trigger travis.ci again.

**Comment by CraZySacX** [comment]
Looks like close open is the easiest way to restart the build.   You can also try ```git commit --allow-empty -m "Trigger"``` per http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit, but I haven't tested that.

**Pull request merged**
